### ISSUE TITLE
font scaling

### ISSUE THREAD

**Issue by muiem11** [maributt/FFLogsLookupPlugin#2]
could you add a font scaling or a slider to adjust the size (especially for 4k screens)

https://i.imgur.com/wrcI7jc.png

**Comment by maributt** [comment]
Sure thing! I'll also redo the positioning calculation since it's a little wonky atm, thanks for the feedback

**Comment by maributt** [comment]
Unfortunately... after looking into this again I realized that it doesn't seem to be possible to scale only select bits of text.

What that means is the only current workaround I see is for you to tweak Dalamud's global UI scaling setting using `/xlsettings`  under the `Look & Feel` tab, I've adjusted how the spacing is calculated based on the font size so that it'll display correctly that way. 

I have plans of injecting text elements into the character inspect window directly in the future (instead of solely relying on ImGui) so this means it'll just scale with the game's built-in scaling system and solve that issue entirely but for now this is the best workaround I can offer, hope this helps!
